# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13WYdqID4EOLhb4sFOCTldQ30YGU_-n7o
"""

import pandas as pd
from google.colab import files
from IPython.display import display

def cargar_y_procesar_reportes():
    print("📂 Subí los dos archivos CSV descargados desde Marfeel:")
    archivos_subidos = files.upload()

    if len(archivos_subidos) != 2:
        raise ValueError("Debés subir exactamente dos archivos.")

    archivos = list(archivos_subidos.keys())

    # Cargar CSVs
    df1 = pd.read_csv(archivos[0])
    df2 = pd.read_csv(archivos[1])

    # Normalizar columnas
    def normalizar_columnas(df):
        df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
        return df

    df1 = normalizar_columnas(df1)
    df2 = normalizar_columnas(df2)

    # Detectar cuál es el de fuentes y cuál el de totales
    if 'sourceinternal' in df1.columns:
        df_fuentes = df1
        df_totales = df2
    else:
        df_fuentes = df2
        df_totales = df1

    # Agrupar fuentes por título
    df_fuentes_agg = df_fuentes.groupby(['title', 'sourceinternal'])['pageviewstotal'].sum().reset_index()

    # Determinar fuente principal
    idx_max = df_fuentes_agg.groupby('title')['pageviewstotal'].idxmax()
    df_fuente_principal = df_fuentes_agg.loc[idx_max].reset_index(drop=True)
    df_fuente_principal = df_fuente_principal.rename(columns={
        'pageviewstotal': 'pageviews_fuente_principal',
        'sourceinternal': 'fuente_principal'
    })

    # Unir con totales
    df_final = pd.merge(df_totales, df_fuente_principal, on='title', how='left')

    # Calcular porcentaje de fuente principal
    df_final['porcentaje_fuente_principal'] = (
        df_final['pageviews_fuente_principal'] / df_final['pageviewstotal'] * 100
    ).round(2)

    # Resultado final ordenado
    resultado = df_final[['title', 'pageviewstotal', 'fuente_principal', 'porcentaje_fuente_principal']]
    resultado = resultado.sort_values(by='pageviewstotal', ascending=False).reset_index(drop=True)

    return resultado

# Ejecutar procesamiento
resultado = cargar_y_procesar_reportes()

# Mostrar top 20
display(resultado.head(20))

# Función auxiliar: filtro temático por palabra clave
def filtrar_por_tema(df, palabra_clave):
    palabra = palabra_clave.lower()
    filtrado = df[df['title'].str.lower().str.contains(palabra, na=False)].copy()
    return filtrado.reset_index(drop=True)

filtrar_por_tema(resultado, "Peñarol")

!pip install -U spacy
!python -m spacy download es_core_news_sm

import spacy
nlp = spacy.load('es_core_news_sm')

# Análisis 1: Longitud del título (en caracteres)
resultado['longitud_titulo'] = resultado['title'].apply(len)

# Vista previa con la nueva variable
display(resultado[['title', 'longitud_titulo', 'pageviewstotal', 'fuente_principal']].head(10))

import re

# Función combinada de extracción de entidades
def extraer_entidades(titulo):
    doc = nlp(titulo)

    # Entidades detectadas automáticamente por spaCy
    entidades_spacy = [ent.text for ent in doc.ents if ent.label_ in ("PER", "ORG", "LOC")]

    # Detección manual de entidades locales por coincidencia exacta como palabra (case insensitive)
    entidades_locales_encontradas = [
        ent for ent in entidades_locales_uy
        if re.search(rf'\b{re.escape(ent)}\b', titulo, flags=re.IGNORECASE)
    ]

    # Combinar y eliminar duplicados
    entidades_total = list(set(entidades_spacy + entidades_locales_encontradas))
    return entidades_total

# Aplicar al DataFrame
resultado["entidades"] = resultado["title"].apply(extraer_entidades)

# Variable booleana: ¿el título tiene entidades?
resultado["tiene_entidades"] = resultado["entidades"].apply(lambda x: len(x) > 0)

# Contador: ¿cuántas entidades tiene el título?
resultado["cantidad_entidades"] = resultado["entidades"].apply(len)

# Vista previa
display(resultado[["title", "entidades", "tiene_entidades", "cantidad_entidades", "pageviewstotal"]].head(10))

# ──────────────────────────────────────────────────────────────
#  Análisis 3 – Tono del título (interrogativo / exclamativo)
# ──────────────────────────────────────────────────────────────

# Palabras / frases que suelen introducir preguntas implícitas
palabras_interrogativas = [
    # básicas
    "qué", "quién", "quiénes", "cuándo", "cómo", "dónde", "cuál", "cuáles",
    "por qué", "para qué",
    # ampliadas (uso local)
    "qué pasó con", "qué dice", "qué opinan", "qué se sabe",
    "quién es", "cuánto cuesta", "hasta cuándo",
    "cómo funciona", "por qué ahora", "va a cambiar", "es verdad que"
]

# Expresiones que marcan sorpresa / énfasis (sin signos)
expresiones_exclamativas = [
    # básicas
    "insólito", "sorprendente", "impresionante", "increíble",
    "no lo vas a creer", "dramático", "emotivo", "desgarrador", "escándalo",
    # ampliadas (uso local)
    "atención", "alerta", "de película", "de no creer", "polémico",
    "conmoción", "indignación", "impactante", "grave denuncia",
    "inesperado", "histórico", "se viralizó", "fuertes imágenes",
    "reacción en redes", "revelación", "testimonio desgarrador", "rompió el silencio",
    "estalló"
]

def clasificar_tono(titulo: str) -> str:
    t_low = titulo.lower()

    # 1. Signos explícitos
    if any(s in titulo for s in ["?", "¿"]):
        return "interrogativo"
    if any(s in titulo for s in ["!", "¡"]):
        return "exclamativo"

    # 2. Patrones implícitos
    if any(frase in t_low for frase in palabras_interrogativas):
        return "interrogativo"
    if any(frase in t_low for frase in expresiones_exclamativas):
        return "exclamativo"

    return "neutro"

# ─ Aplicar al DataFrame (ya existente) ─
resultado["tono_titulo"] = resultado["title"].apply(clasificar_tono)

# Vista rápida
from IPython.display import display
display(
    resultado[["title", "tono_titulo", "pageviewstotal", "fuente_principal"]]
    .head(30)
)

import re

def detectar_cita(titulo: str) -> str:
    # Busca contenido entre comillas dobles (tipográficas o rectas)
    return "Sí" if re.search(r'["“”](.+?)["“”]', titulo) else "No"

# Aplicar al DataFrame
resultado["tiene_cita"] = resultado["title"].apply(detectar_cita)

# Vista rápida
display(resultado[["title", "tiene_cita", "pageviewstotal", "fuente_principal"]].head(15))

# Función para clasificar la posición de la primera entidad encontrada en el título
def posicion_entidad(titulo, entidades):
    if not entidades:
        return "sin_entidades"

    titulo_lower = titulo.lower()
    primera_entidad = None
    pos_entidad = len(titulo)  # valor alto por defecto

    for ent in entidades:
        idx = titulo_lower.find(ent.lower())
        if idx != -1 and idx < pos_entidad:
            pos_entidad = idx
            primera_entidad = ent

    if primera_entidad is None:
        return "sin_entidades"

    longitud = len(titulo)
    proporcion = pos_entidad / longitud

    if proporcion <= 0.25:
        return "inicio"
    elif proporcion >= 0.75:
        return "final"
    else:
        return "medio"

# Aplicar al DataFrame
resultado["posicion_entidad"] = resultado.apply(
    lambda row: posicion_entidad(row["title"], row["entidades"]),
    axis=1
)

# Vista previa
resultado[["title", "entidades", "posicion_entidad", "pageviewstotal"]].head(10)

# Función para detectar el estilo narrativo o informativo
def detectar_estilo_titulo(titulo):
    doc = nlp(titulo)
    verbos = [token for token in doc if token.pos_ == "VERB"]

    # Si hay verbos conjugados en pasado o presente, probablemente sea narrativo
    tiempos_narrativos = {"Pres", "Past", "Imp", "Ind"}
    verbos_conjugados = [
        v for v in verbos if v.morph.get("Tense") and any(t in v.morph.get("Tense") for t in tiempos_narrativos)
    ]

    # Si hay muchos sustantivos pero ningún verbo conjugado → probablemente informativo
    sustantivos = [token for token in doc if token.pos_ == "NOUN"]

    if len(verbos_conjugados) > 0:
        return "narrativo"
    elif len(sustantivos) > 3 and len(verbos_conjugados) == 0:
        return "informativo"
    else:
        return "informativo"

# Aplicar al DataFrame
resultado["estilo_titulo"] = resultado["title"].apply(detectar_estilo_titulo)

# Vista previa
resultado[["title", "estilo_titulo", "pageviewstotal"]].head(10)

# Lista confirmada de verbos declarativos
verbos_declarativos = [
    "anunció", "anunciará", "confirmó", "confirmará", "decidió", "decidirá",
    "rechazó", "rechazará", "defendió", "defenderá", "cuestionó", "cuestionará",
    "propuso", "propondrá", "sostuvo", "sostendrá", "denunció", "denunciará",
    "convocó", "convocará", "presentó", "presentará", "pidió", "pedirá",
    "apoyó", "apoyará", "criticó", "criticarán", "celebró", "celebrará"
]

# Función para clasificar el estilo del título
def clasificar_estilo_titulo(titulo, entidades, verbos_declarativos):
    doc = nlp(titulo)

    tokens = [token.text.lower() for token in doc]
    tokens_verbos = [token for token in doc if token.pos_ == "VERB"]
    tokens_nombres = [token for token in doc if token.pos_ in ("PROPN", "NOUN")]

    # 1. Declarativo: contiene verbo declarativo + al menos una entidad
    if any(verbo in tokens for verbo in verbos_declarativos) and entidades:
        return "declarativo"

    # 2. Narrativo: contiene verbo + sujeto o nombre propio
    if tokens_verbos and tokens_nombres:
        return "narrativo"

    # 3. Por descarte
    return "informativo-descriptivo"

# Aplicar la función
resultado["estilo_titulo"] = resultado.apply(
    lambda row: clasificar_estilo_titulo(row["title"], row["entidades"], verbos_declarativos),
    axis=1
)

# Vista previa
display(resultado[["title", "estilo_titulo", "entidades", "pageviewstotal"]].head(10))